apiVersion: v1
kind: Secret 
metadata:
  name: mongodb-secret
type: Opaque
data: 
  mongo-root-username: YWRtaW4=
  mongo-root-password: cGFzc3dvcmQxMjM=
  mongo-web-username: d2ViYWRtaW4=
  mongo-web-password: YWRtaW4xMjM0