- name: create user account with vault encrypted pass 
  hosts: clients 
  remote_user: root 
  vars_files:
    - secret.yaml
  
  tasks:
  - name: create a new user account 
    user: 
      name: user7 
      password: "{{ secret | password_hash('sha512') }}"
      state: present