- name: create user account with playbook encryption
  hosts: clients 
  remote_user: root 
  vars:
    secret: Secure*123
  
  tasks:
  - name: create a new user account 
    user: 
      name: user9 
      password: "{{ secret | password_hash('sha512') }}"
      state: present