apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: nextopsakvt21-scp
spec: 
  provider: azure
  parameters: 
    usePodIdentity: "false"
    useVMManagedIdentity: "true"
    userAssignedIdentityID: 1dfd0d69-ac56-4b40-a4d7-2734d38768fd 
    keyvaultName: nextopsakvt21
    cloudName: ""
    objects: | 
      array:
        - |
          objectName: mongodbpass
          objectType: secret
          objectVersion: ""
    tenantId: "9085ff8c-8807-4ff8-a403-ea470525cda6"
  secretObjects:
  - data: 
    - key: key
      objectName: mongodbpass
    secretName: mongodbpass
    type: Opaque