- name: create multiple user accounts
  hosts: clients 
  remote_user: root

  vars: 
    users_list:
      - username: user1
        uid: 10010
        shell: /bin/bash
      - username: user2
        uid: 10011
        shell: /bin/sh
      - username: user3
        uid: 10012
        shell: /bin/bash
  
  tasks: 
    - name: creating multiple user accounts 
      user: 
        name: "{{ item.username }}"
        uid: "{{ item.uid }}"
        shell: "{{ item.shell }}"
        state: present 
      with_items: "{{ users_list }}"