apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: mongodb-sm
  labels:
    release: prometheus-stack
spec:
  selector:
    matchLabels:
      app: mongodb-exporter
  namespaceSelector:
    matchNames:
    - mongodb
  endpoints:
  - port: metrics
    interval: 30s