apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-lb-deploy
  labels: 
    app: nginx-lb-deploy
spec:
  selector:
    matchLabels:
      app: nginx-lb-deploy
  template:
    metadata:
      labels:
        app: nginx-lb-deploy
    spec:
      containers:
      - name: nginx-lb
        image: nginx
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-lb-service
  labels: 
    app: nginx-lb-deploy
spec:
  selector:
    app: nginx-lb-deploy
  ports:
  - port: 80
    targetPort: 80
  type: LoadBalancer

