apiVersion: apps/v1
kind: Deployment
metadata:
  name: probe-example-deployment
  labels:
    app: probe-example
spec:
  replicas: 1
  selector:
    matchLabels:
      app: probe-example
  template:
    metadata:
      labels:
        app: probe-example
    spec:
      containers:
      - name: nginx
        image: nginx:latest
        ports:
        - containerPort: 80
        livenessProbe:                  # Liveness Probe
          httpGet:                      # Check HTTP path
            path: /health               # Replace with your app's health endpoint
            port: 80
          initialDelaySeconds: 5        # Wait 5 seconds before the first check
          periodSeconds: 10             # Check every 10 seconds
        readinessProbe:                 # Readiness Probe
          httpGet:
            path: /ready                # Replace with your app's readiness endpoint
            port: 80
          initialDelaySeconds: 5        # Wait 5 seconds before the first check
          periodSeconds: 5              # Check every 5 seconds
        startupProbe:                   # Startup Probe
          httpGet:
            path: /start                # Replace with your app's startup endpoint
            port: 80
          initialDelaySeconds: 30       # Wait 30 seconds before the first check
          periodSeconds: 10             # Check every 10 seconds
