apiVersion: v1 
kind: ResourceQuota
metadata:
  name: dev-team-quota
  namespace: dev-team
spec:
  hard:
    requests.cpu: "1" #minimum
    requests.memory: "1Gi"
    limits.cpu: "2" #maximum
    limits.memory: "2Gi"
    pods: "10"